# Generated by Django 3.2.5 on 2021-10-25 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='marca',
            table='appPedidos_marca',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='appPedidos_pedido',
        ),
        migrations.AlterModelTable(
            name='productopedido',
            table='appPedidos_productopedido',
        ),
    ]
