# Generated by Django 3.2.8 on 2021-10-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('disponible', models.CharField(choices=[('n', 'NO'), ('s', 'SI')], max_length=1)),
            ],
        ),
    ]
