# Generated by Django 3.2.8 on 2021-10-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuno', '0002_auto_20211028_2027'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='appPedidos_producto',
        ),
    ]
